### ISSUE TITLE
Output part size used when splitting big files exceeds the max part size used by HOS in directories with the archive bit set.

### ISSUE THREAD

**Issue by Bakuryu** [DarkMatterCore/nxdumptool#32] opened 2019-08-01 12:32 UTC
Through tons of trouble shooting I have determined what seems like an issue with how your tool splits the data.arc file when its dumped. Using the latest version dumping the romfs with an update and then moving,renaming, and then archiving in a folder of the same name so it can be used on a fat32 sd card for modding does not work. However if you conjoin the parts and then re-split them using [splitNSP](https://github.com/AnalogMan151/splitNSP/releases) and do the same preparation steps, it works. The only difference thus far I can see between the files when they are split is there size. Here you can see the splitnsp one on the left and the original split ones from your tool on the right.

![Filesizecamparison](https://user-images.githubusercontent.com/3741180/62293231-18ded080-b436-11e9-8a03-54f48f1dcfb0.png)

When compared using HxD it noted that while the files were identical the file sizes were different.

![hexcomparison](https://user-images.githubusercontent.com/3741180/62293288-41ff6100-b436-11e9-9c1c-70cb632678ce.png)

While I don't get how they can be identical if they are different sizes I have one last test to verify if its just size which is to use 7zip to split the files at using identical sizes that splitnsp uses to see if it really is just file size, but HxD seems to make that the case.

**Comment by DarkMatterCore** [comment] 2019-08-01 12:49
Well, it's not splitting incorrectly, per se - otherwise, you wouldn't be able to generate a full data.arc file by merging its parts, which is what the application aims to achieve anyway.

Currently, a different split file size is used for anything that's not a XCI nor a NSP. This includes files extracted from the RomFS section of a title.

Setting the split file size to the same one used for NSPs should do the trick, since that's also the size used by splitNSP.

HOS probably detects that the file size for part `00` exceeds the maximum split file size for a file inside a directory with the archive bit set, resulting in an unexpected behaviour.

**Comment by DarkMatterCore** [comment] 2019-08-17 02:16
Fixed in ed45a863faa0524d9701dc6a87bc1f51209430eb.

**Closed by DarkMatterCore** 2019-08-17 02:16 UTC
Labels: enhancement
