### ISSUE TITLE
sha256 checksum mismatch error

### ISSUE THREAD

**Issue by Kylacia** [DarkMatterCore/nxdumptool#153] opened 2023-12-17 23:17 UTC
**Describe the bug**
After updating to 17.0.0 and updating sigpatches and lockpick and using the NX Rewrite, any time I try to dump a base installation I receive the following error:

**To Reproduce**
1. Go to 'user titles menu > game > nsp dump options > dump base application > start nsp dump'
2. After completing, I receive sha256 checksum mismatch

**Please fill the following information:**
- Horizon OS (Switch FW) version: [17.0.0]
- CFW: Atmosphere
- CFW version: (Sorry, I'm not sure.  I believe the most recent release)
- Atmosphère launch method (if applicable): Hekate
- nxdumptool version: [rewrite -found on this page when you suggested someone use a certain build and you linked it]
- Homebrew launch method: [title override]
- Source storage used with the application (if applicable): [SD]
- SD card specs: [e.g. Samsung EVO 512 GB, FAT32 partition]

**Screenshots**
![image](https://github.c
![ss](https://github.com/DarkMatterCore/nxdumptool/assets/154098743/b556381b-fcd9-411f-8de4-e3b189da6e5a)
om/DarkMatterCore/nxdumptool/assets/154098743/efe6e098-c11d-4949-9cf5-0be01b2947a5).

**Logfile**
If available, please upload your logfile located at `sdmc:/nxdumptool/nxdumptool.log`.

**Additional context**
It looks like I was successful in dumping some updates, but nothing that was made from a gamecard that was installed using tinfoil.  Copying a game card itself worked successfully.

**Comment by DarkMatterCore** [comment] 2023-12-22 11:33
This is not a bug -- it's a feature. If a dumped NCA doesn't pass the checksum validation steps while creating an output NSP, the whole dump process is immediately cancelled. This is done to make sure the application doesn't end up dumping corrupted data.

The reason why the checksum validation fails is because one or more of the NCAs from this game have been modified and the CNMT wasn't updated accordingly, which is completely out of nxdumptool's scope.

**Comment by DarkMatterCore** [comment] 2024-01-20 22:13
I'm closing this issue.

**Closed as completed by DarkMatterCore** 2024-01-20 22:13 UTC
Labels: invalid
