### ISSUE TITLE
Dumps made by NXDumpTool  Cause corruption in NSCBuilder custom files

### ISSUE THREAD

**Issue by pcwizard7** [DarkMatterCore/nxdumptool#59] opened 2020-05-12 18:48 UTC
**Describe the bug**
no matter what settings I use to dump games in nxdumptool with change Program NSA / remove console data etc. The file will verify fine in ntdb but as soon as i try to either repack it a game into xci or combine a base + update files into one. the created file is corrupt and won't launch and error out  on the switch 

I found its NXdumptool because i made new dump of game with sxdumper and created a custom file and pass verify and can launch the game

**To Reproduce**
1. you can use either option 1 or 2 in NSC builder I suggest 2 even if ur only repack a single file
2. use option 4 > option 8 to verify if there's a corruption  of the newly created file from the NSC
3. you can try to install the game or if u have sxos mount it as xci and see if it can run on the switch

**Please fill the following information:**
- Horizon OS (Switch FW) version: 10.0.2
- CFW: SX OS, 
- CFW version: 2.9.5
- NXDumpTool version: 1.1.10
- Homebrew launch method: Both [title override, applet]
- SD card specs: Scandisk Ultra FAT32

**Comment by DarkMatterCore** [comment] 2020-05-12 18:55
@pcwizard7 Hi there. Thanks for opening this issue report.

If possible, please hit me up in Discord. My handle is available in my GitHub profile page.

**Comment by pcwizard7** [comment] 2020-05-12 19:35
@DarkMatterCore sent u friend request its real late atm so can't really talk but leave any messages you want too and i get back to you

**Comment by DarkMatterCore** [comment] 2020-06-02 04:52
Update: preliminary analysis suggests that NSC_Builder is specifically patching both Key Generation fields in NCAs from NSPs dumped with nxdumptool. Further analysis is required and will be carried out.

**Comment by DarkMatterCore** [comment] 2020-06-02 19:16
Further analysis of the NSP dumps suggest that their NCAs within, as well as their certificate chains and tickets, are all identical. There's really nothing that should be preventing the gamecard images generated by NSC_Builder, based on nxdumptool NSPs, from working.

@pcwizard7 was kind enough to provide logfiles from NUT for additional insight, using NSP dumps from `PC Building Simulator` generated with both nxdumptool and SXDumper.

[010072800cbe8000_NUT_logs.zip](https://github.com/DarkMatterCore/nxdumptool/files/4719186/010072800cbe8000_NUT_logs.zip)

NSC_Builder is most likely triggering some custom behaviour specifically for nxdumptool NSPs.

**Comment by DarkMatterCore** [comment] 2020-06-06 16:35
We discovered that repacking nxdumptool NSPs using tools such as hactoolnet is enough to get them to work properly with NSC_Builder. XMLs and JPGs were removed before generating the new packages with hactoolnet, which use PFS0 headers aligned to a 0x20-byte boundary.

However, after some additional tests using custom nxdumptool builds without XML/JPG generation and PFS0 header aligning to a 0x20-byte boundary, we were unable to get the generated XCIs to work using these new NSP dumps. The only clear difference that can be identified between these new dumps and hactoolnet repacks is the PFS0 file order - all packed files are identical.

This makes me think PFS0 file order detection/handling is at fault in NSC_Builder.

**Comment by pcwizard7** [comment] 2020-06-07 15:41
reminder awaiting reply in discord thanks

**Comment by julesontheroad** [comment] 2020-06-09 13:52
The order doesn't matter headers are read and the order is decided by the cnmt to match Nintendo behavour.
I imagine the issue is on the tickets, probably some part of the function used uses my old code, more based on nut and more ticket dependant. The expected format of the ticket is scene format which was based on update tickets with the introduction of new flags in tickets nxdumptool tries to include it while the rest of the dumpers ignore them, i fixed it the first time it happened in the ticket library, my best guess is it happened again and is better to readapt all the functions to ignore tickets except for titlekeys.
I would have to look into the dump itself but i'm 100% sure is unrelated to file order specially since NSCB also uses the cnmt order. I don't know when i'll have time to check though i'm pretty busy with work.

**Comment by DarkMatterCore** [comment] 2020-06-09 14:42
@julesontheroad Thanks for your insight on this matter. What led me to believe it's a file order problem is the fact that unpacking the NSP and repacking it using hactoolnet or similar tools fixes the issue  - the contents of the ticket itself are not changed in the process.

I'm recovering from an almost 48-hour long blackout, so at this moment I just don't have the energy to sit down and take a look at this or other issues (quite frankly, I want to rest for the next few hours).

@pcwizard7 Would you be able to follow Jules' indications from the open NSC_Builder issue and test nxdumptool NSPs with a beta build? Hopefully the results will vary.

**Comment by julesontheroad** [comment] 2020-06-09 15:12
@DarkMatterCore Sorry to hear about your last 48h man. Don't worry about the issue at the end is on my end, I already was planning to change all that stuff to avoid that kind of issues. If it's related to ticket flags as I expect I'll solve it on my end.

**Comment by julesontheroad** [comment] 2020-06-09 18:02
@DarkMatterCore @pcwizard7 I went and dump that same game and update with latest nxdumptool, in latest SX OS with FW 10.03 on the switch, using the same options. Then I did a verification with my tool, etc... and i didn't find issues. My first test test was with the beta and the second with the 0.98b exe from some months back.
I also tested the update in the text files. I actually didn't even find new flags in the tickets of either game or update so I don't really get what's the issue here but since pcwizard7 opened an issue in my git i would close this one, i can try to help him from there.

**Comment by DarkMatterCore** [comment] 2020-06-09 18:15
@julesontheroad Thanks a lot for doing these additional tests, mate. It would be nice to know which NSC_Builder version is @pcwizard7 using.

Just in case, I'll keep an eye out for the open NSC_Builder issue and close this one for the time being. If something arises (which I doubt anyway), I will reopen this issue.

**Closed by DarkMatterCore** 2020-06-09 18:15 UTC
Labels: invalid
