### ISSUE TITLE
Splits data.arc into multiple files on exfat

### ISSUE THREAD

**Issue by SuperMario20** [DarkMatterCore/nxdumptool#28] opened 2019-06-29 15:49 UTC
When I dump the romfs from Smash Ultimate it splits it into multiple files even though I have an exFat sd card and plenty of space. Also I can't use a split data.arc file for smash ultimate modding so it makes the data.arc file unusable.

**Comment by DarkMatterCore** [comment] 2019-06-29 16:47
This is basically a duplicate of issue #11. And yes, this is an expected behaviour.

There's no way to automatically tell if the SD card partition is exFAT or not without modifying the CFW or adding a custom KIP module, so the default action is to just split any big files extracted from HFS0/ExeFS/RomFS. FS services don't expose any kind of raw storage handle for rhe SD card.

Just use `copy /b data.arc.00+...+data.arc.nn data.arc` (Windows) or `cat data.arc.00 ... data.arc.nn > data.arc` (Linux). `nn` is the number for the last part, make sure you include all parts in the command line.

**Closed by DarkMatterCore** 2019-06-29 16:47 UTC
