### ISSUE TITLE
NXDumpTool wont let me dump nsp

### ISSUE THREAD

**Issue by dakrl3ol3** [DarkMatterCore/nxdumptool#137] opened 2023-10-13 06:25 UTC
I try dumping the title and it says i have no keys in the switch folder and to dump using lockpick_rcm. I have been using nxdump tool for a while now and never had problems and needless to say i had dumped my keys using lockpick_rcm already. I redumped the keys, still doesn't work. I'm pretty sure im up to date on everything, but re-download new versions of lockpick_rcm, nxdumptool and atmosphere and still gives the same error. The only thing i can think of is that i had an update on my switch before this issue started. Thanks in advance and thank you so much for the wonderful tool that has honestly worked flawlessly until now.

**Comment by DarkMatterCore** [comment] 2023-10-13 07:35
Hi there. Thank you for the kind comments.

Could you please provide more details about your current setup?

**Comment by MSco** [comment] 2023-10-13 08:17
@DarkMatterCore I have similar issues. 

When trying do dump a game Update as nsp, nxdumptool says 
`decryptNcaHeader: invalid NCA magic word! Wrong header key? (0x5FA22CA9)` 
`Try running Lockpic_RCM to generate the keys file from scratch`

On HOS 16.0 (emummc), everything works fine. The issue occurs only on the new 17.0 (sysmmc).

Of course, I also redumped my keys using the new Lockpic_RCM 1.9.11, but the issue is the same.

My setup: 
SYSMMC
HOS: 17.0
nxdumptool: 1.1.15
atmosphere 1.6.0,
hekate: 6.0.7
Lockpick_RCM: v1.9.11

**Comment by paulober** [comment] 2023-10-13 11:09
Same here. I have a launch switch model. 
- 64 GB microSD
- hekate 6.0.7
- atmosphere 1.6.0
- Lockpick_RCM: v1.9.11
- HOS 17.0.0
- nxdumptool 1.1.15

When trying to dump a dlc:
```
decryptNcaHeader: invalid NCA magic word! Wrong header key? (0x44540316)
Try running Lockpick_RCM to generate the keys file from scratch.
```

And when trying to dump update for the same game:
```
decryptNcaHeader: invalid NCA magic word! Wrong header key? (0x5F39E4B8)
Try running Lockpick_RCM to generate the keys file from scratch.
```

The game is a game card game and the update and dlc is in system memory.

**Comment by paulober** [comment] 2023-10-13 11:11
For a fast solution where does nxdumptool want us to put the manually extracted Lockpick_RCM output?

**Comment by paulober** [comment] 2023-10-13 13:03
I just saw that the repository already contains a fix for 17.0.0 thought the binary is not uploaded in releases. I'll try to use the the updated version...

**Comment by paulober** [comment] 2023-10-13 14:00
The latest build worked for me: https://github.com/DarkMatterCore/nxdumptool/actions/runs/6493796629

**Comment by DarkMatterCore** [comment] 2023-10-16 16:08
Please check the [latest pre-release](https://github.com/DarkMatterCore/nxdumptool/releases/tag/rewrite-prerelease). I'll close this issue.

**Closed as completed by DarkMatterCore** 2023-10-16 16:08 UTC

**Comment by omegahack0** [comment] 2024-03-08 20:06
I am getting this same issue on 17.0.1
Sometimes it gives the error above other times, it will give the error
findKeyInProcessMemory: unable to locate key "header_key_source" in process memory!

**Comment by Whovian9369** [comment] 2024-03-08 20:07
> I am getting this same issue on 17.0.1 

Please check the [latest pre-release](https://github.com/DarkMatterCore/nxdumptool/releases/tag/rewrite-prerelease).

**Comment by SauravChittal** [comment] 2025-01-08 11:17
Now I'm getting the same issue on 19.0.1

**Comment by KidouYu** [comment] 2025-01-10 19:32
Same issue as Saura

**Comment by DarkMatterCore** [comment] 2025-01-10 19:44
@SauravChittal @KidouYu redump your console keys with an up-to-date Lockpick_RCM build and use the [latest nxdumptool pre-release build](https://github.com/DarkMatterCore/nxdumptool/releases/tag/rewrite-prerelease).

We can't tell you where to get newer Lockpick_RCM builds -- you're on your own with that.
