### ISSUE TITLE
Unable to retrieve the game card Title ID!

### ISSUE THREAD

**Issue by postcert** [DarkMatterCore/nxdumptool#8] opened 2018-07-13 13:03 UTC
The error mentions being above the cartridge's FW, but my system is on 5.1.0 so these 2.1 and 3.1 carts shouldn't be erroring.

Is network connectivity necessary to download the XML db?

**Comment by DarkMatterCore** [comment] 2018-07-13 13:28
Which method are you using to launch the application? All the reports I have received regarding this error have actually been related to the system FW version being lower than the one on the game card.

Yes, network connectivity is required to download the NSWDB XML, but it isn't mandatory. It is only needed for dump verification, which is totally optional.

However, you may need to connect your console to Internet at least once to fix a nasty NCM service bug. Please take a look at issue #7 .

**Comment by postcert** [comment] 2018-07-13 14:01
I've been running it through nx-hbmenu v2.0 (newest release) and SXOS 1.3.
From what I understand in issue #7 the switch had never been connected to the internet all together, but I've used my switched for ~6 months online prior and updated to 5.1 online before going on airplane mode for SXOS usage.

btw: I bought a fresh switch yesterday which should work for another issue #7 test case.

**Comment by DarkMatterCore** [comment] 2018-07-13 16:47
It must be connected to the Internet at least once while using a CFW (Hekate/SX OS). I haven't been able to test the application under SX OS myself, though. But most tests performed by other users suggest this fixes the problem. If a possible ban concerns you, then block the "receive-lp1" domains in your router to avoid that.

Public releases of the WAIN dumper do not use the NCM and NS services to retrieve the game card metadata, so it's out of the question.

**Comment by postcert** [comment] 2018-07-13 18:10
Sounds great, I'll give that a chance after setting up a proxy.

**Comment by DarkMatterCore** [comment] 2018-07-23 03:17
@postcert 

The hang up at the "Please wait" screen has been fixed with commit 7a94da0a5c452b9080fa1fc2e9d8af82ab3637a8. Turned out to be a problem with the time functions from the standard C library. The application is now using the time service from the Switch.

I'll leave this issue open because it's still weird that the application can't read the metadata from game cards with a bundled firmware update lower than the version currently installed on the console. If it ever happens again, I'll try to debug it.

**Comment by TheSerafan** [comment] 2018-08-10 17:17
I have the same problem. My firmware is at 5.1, but supposedly it's not high enough to  dump the cartridge. 

I get the same error message.

**Comment by DarkMatterCore** [comment] 2019-04-22 17:16
@TheSerafan @postcert 

Hi there. Sorry for taking so long to answer, a lot of things have happened in my personal life in the past few months, and they have kept me busy enough to stop browsing the Internet as much as I'd like.

Could you please try out the attached test build? I want to find out if this bug can still be reproduced on it.

[gcdumptool_test_20190422.zip](https://github.com/DarkMatterCore/gcdumptool/files/3104155/gcdumptool_test_20190422.zip)

**Comment by DarkMatterCore** [comment] 2019-06-23 12:31
Two months have passed and I haven't received any other report about this problem.

If it ever happens again, please, feel free to reopen this issue.

**Closed** 2019-06-23 12:31 UTC
Labels: question
